import { db, functionsTable } from "@workspace/db";
import { randomUUID } from "crypto";

const functions = [
  // Technical Analysis
  {
    id: randomUUID(),
    name: "trend_strength_adx",
    category: "technical",
    description: "Average Directional Index used to determine whether a trend exists and how strong it is.",
    signature: "trend_strength_adx(highs: number[], lows: number[], closes: number[], period?: number): number",
    codeExample: `const adx = trend_strength_adx(highs, lows, closes, 14);
if (adx > 25) console.log("Strong trend");`,
    parametersJson: JSON.stringify([
      { name: "highs", type: "number[]", description: "High-price series" },
      { name: "lows", type: "number[]", description: "Low-price series" },
      { name: "closes", type: "number[]", description: "Close-price series" },
      { name: "period", type: "number", description: "Lookback period", optional: true },
    ]),
    returns: "ADX value between 0 and 100",
    tagsJson: JSON.stringify(["trend", "strength", "directional-movement"]),
  },
  {
    id: randomUUID(),
    name: "relative_strength_vs_benchmark",
    category: "technical",
    description: "Measures whether the asset is outperforming or underperforming a benchmark over the same lookback period.",
    signature: "relative_strength_vs_benchmark(prices: number[], benchmarkPrices: number[], period?: number): number",
    codeExample: `const spread = relative_strength_vs_benchmark(assetPrices, indexPrices, 20);
if (spread > 0) console.log("Outperforming benchmark");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Asset close-price series" },
      { name: "benchmarkPrices", type: "number[]", description: "Benchmark close-price series" },
      { name: "period", type: "number", description: "Relative-strength lookback", optional: true },
    ]),
    returns: "Relative performance spread in percentage points",
    tagsJson: JSON.stringify(["relative-strength", "benchmark", "leadership"]),
  },
  {
    id: randomUUID(),
    name: "momentum_rate_of_change",
    category: "technical",
    description: "Measures the speed of price movement by comparing current price with price N periods ago.",
    signature: "momentum_rate_of_change(prices: number[], period?: number): number",
    codeExample: `const roc = momentum_rate_of_change(prices, 12);
if (roc > 0) console.log("Positive momentum");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Ordered price series" },
      { name: "period", type: "number", description: "ROC lookback", optional: true },
    ]),
    returns: "Percentage rate of change",
    tagsJson: JSON.stringify(["momentum", "velocity", "roc"]),
  },
  {
    id: randomUUID(),
    name: "rsi_regime_analysis",
    category: "technical",
    description: "Uses RSI persistence rather than a single snapshot to detect sustained buying or selling pressure.",
    signature: "rsi_regime_analysis(prices: number[], period?: number): number",
    codeExample: `const regime = rsi_regime_analysis(prices, 14);
if (regime >= 60) console.log("Bullish RSI regime");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Close-price series" },
      { name: "period", type: "number", description: "RSI lookback", optional: true },
    ]),
    returns: "Regime score between 0 and 100",
    tagsJson: JSON.stringify(["rsi", "regime", "pressure"]),
  },
  {
    id: randomUUID(),
    name: "macd_histogram_slope",
    category: "technical",
    description: "Measures momentum acceleration or deceleration by observing the slope of the MACD histogram.",
    signature: "macd_histogram_slope(prices: number[], fast?: number, slow?: number, signal?: number): number",
    codeExample: `const slope = macd_histogram_slope(prices, 12, 26, 9);
if (slope > 0) console.log("Momentum is accelerating");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Close-price series" },
      { name: "fast", type: "number", description: "Fast EMA period", optional: true },
      { name: "slow", type: "number", description: "Slow EMA period", optional: true },
      { name: "signal", type: "number", description: "Signal EMA period", optional: true },
    ]),
    returns: "Signed slope value",
    tagsJson: JSON.stringify(["macd", "momentum", "acceleration"]),
  },
  {
    id: randomUUID(),
    name: "realized_volatility",
    category: "technical",
    description: "Computes observed market uncertainty from the standard deviation of actual realized returns.",
    signature: "realized_volatility(returns: number[], annualizationFactor?: number): number",
    codeExample: `const vol = realized_volatility(dailyReturns, 252);
if (vol > 30) console.log("High realized volatility");`,
    parametersJson: JSON.stringify([
      { name: "returns", type: "number[]", description: "Periodic return series" },
      { name: "annualizationFactor", type: "number", description: "Annualization factor such as 252", optional: true },
    ]),
    returns: "Annualized volatility percentage",
    tagsJson: JSON.stringify(["volatility", "risk", "realized"]),
  },
  {
    id: randomUUID(),
    name: "atr_expansion_contraction",
    category: "technical",
    description: "Detects volatility regime shifts by measuring whether Average True Range is expanding or contracting.",
    signature: "atr_expansion_contraction(highs: number[], lows: number[], closes: number[], period?: number): number",
    codeExample: `const regimeShift = atr_expansion_contraction(highs, lows, closes, 14);
if (regimeShift > 0) console.log("ATR expansion underway");`,
    parametersJson: JSON.stringify([
      { name: "highs", type: "number[]", description: "High-price series" },
      { name: "lows", type: "number[]", description: "Low-price series" },
      { name: "closes", type: "number[]", description: "Close-price series" },
      { name: "period", type: "number", description: "ATR lookback", optional: true },
    ]),
    returns: "Signed regime-shift score",
    tagsJson: JSON.stringify(["atr", "volatility", "regime"]),
  },
  {
    id: randomUUID(),
    name: "bollinger_band_width",
    category: "technical",
    description: "Measures compression and expansion phases using the width between upper and lower Bollinger Bands.",
    signature: "bollinger_band_width(prices: number[], period?: number, stdDev?: number): number",
    codeExample: `const width = bollinger_band_width(prices, 20, 2);
if (width < 0.05) console.log("Compression setup");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Price series" },
      { name: "period", type: "number", description: "Band lookback", optional: true },
      { name: "stdDev", type: "number", description: "Standard deviation multiplier", optional: true },
    ]),
    returns: "Normalized band width ratio",
    tagsJson: JSON.stringify(["bollinger", "volatility", "compression"]),
  },
  {
    id: randomUUID(),
    name: "volume_profile",
    category: "technical",
    description: "Locates price levels that attracted the highest participation by distributing volume across price zones.",
    signature: "volume_profile(candles: Array<{ high: number; low: number; close: number; volume: number }>, levels?: number): Array<{ price: number; volume: number }>",
    codeExample: `const profile = volume_profile(candles, 12);
const poc = profile.sort((a, b) => b.volume - a.volume)[0];`,
    parametersJson: JSON.stringify([
      { name: "candles", type: "Array<Candle>", description: "OHLCV candle objects" },
      { name: "levels", type: "number", description: "Number of price bins", optional: true },
    ]),
    returns: "Array of price-volume buckets",
    tagsJson: JSON.stringify(["volume", "profile", "participation"]),
  },
  {
    id: randomUUID(),
    name: "vwap_distance",
    category: "technical",
    description: "Measures how far current price is trading from VWAP to estimate institutional positioning.",
    signature: "vwap_distance(candles: Array<{ high: number; low: number; close: number; volume: number }>): number",
    codeExample: `const distance = vwap_distance(sessionCandles);
if (distance > 1.5) console.log("Extended above VWAP");`,
    parametersJson: JSON.stringify([
      { name: "candles", type: "Array<Candle>", description: "Intraday or session candles" },
    ]),
    returns: "Percentage distance from VWAP",
    tagsJson: JSON.stringify(["vwap", "institutional", "extension"]),
  },
  {
    id: randomUUID(),
    name: "on_balance_volume",
    category: "technical",
    description: "Checks whether volume confirms the move by cumulatively adding or subtracting volume on up and down closes.",
    signature: "on_balance_volume(prices: number[], volumes: number[]): number",
    codeExample: `const obv = on_balance_volume(prices, volumes);
if (obv > previousObv) console.log("Volume confirms upside");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Close-price series" },
      { name: "volumes", type: "number[]", description: "Volume series" },
    ]),
    returns: "Cumulative OBV value",
    tagsJson: JSON.stringify(["obv", "volume", "confirmation"]),
  },
  {
    id: randomUUID(),
    name: "accumulation_distribution_line",
    category: "technical",
    description: "Estimates accumulation or distribution by combining close location value with volume.",
    signature: "accumulation_distribution_line(highs: number[], lows: number[], closes: number[], volumes: number[]): number",
    codeExample: `const adLine = accumulation_distribution_line(highs, lows, closes, volumes);
if (adLine > 0) console.log("Accumulation bias");`,
    parametersJson: JSON.stringify([
      { name: "highs", type: "number[]", description: "High-price series" },
      { name: "lows", type: "number[]", description: "Low-price series" },
      { name: "closes", type: "number[]", description: "Close-price series" },
      { name: "volumes", type: "number[]", description: "Volume series" },
    ]),
    returns: "Cumulative accumulation/distribution value",
    tagsJson: JSON.stringify(["smart-money", "volume", "distribution"]),
  },
  {
    id: randomUUID(),
    name: "market_breadth",
    category: "technical",
    description: "Measures how many assets are participating in the move by comparing advancers and decliners.",
    signature: "market_breadth(advancingAssets: number, decliningAssets: number): number",
    codeExample: `const breadth = market_breadth(320, 180);
if (breadth > 0.6) console.log("Broad participation");`,
    parametersJson: JSON.stringify([
      { name: "advancingAssets", type: "number", description: "Count of advancing assets" },
      { name: "decliningAssets", type: "number", description: "Count of declining assets" },
    ]),
    returns: "Breadth ratio between 0 and 1",
    tagsJson: JSON.stringify(["breadth", "participation", "internals"]),
  },
  {
    id: randomUUID(),
    name: "advance_decline_line",
    category: "technical",
    description: "Tracks cumulative net advances to evaluate internal market health over time.",
    signature: "advance_decline_line(netAdvances: number[]): number",
    codeExample: `const adLine = advance_decline_line([120, 85, -40, 140, 60]);
console.log(adLine);`,
    parametersJson: JSON.stringify([
      { name: "netAdvances", type: "number[]", description: "Series of advances minus declines" },
    ]),
    returns: "Cumulative advance-decline line value",
    tagsJson: JSON.stringify(["advance-decline", "breadth", "internals"]),
  },
  {
    id: randomUUID(),
    name: "new_high_new_low_ratio",
    category: "technical",
    description: "Measures leadership strength by comparing new highs against new lows.",
    signature: "new_high_new_low_ratio(newHighs: number, newLows: number): number",
    codeExample: `const ratio = new_high_new_low_ratio(75, 12);
if (ratio > 3) console.log("Strong leadership");`,
    parametersJson: JSON.stringify([
      { name: "newHighs", type: "number", description: "Count of new highs" },
      { name: "newLows", type: "number", description: "Count of new lows" },
    ]),
    returns: "New-high to new-low ratio",
    tagsJson: JSON.stringify(["leadership", "highs-lows", "strength"]),
  },
  {
    id: randomUUID(),
    name: "correlation_to_market",
    category: "technical",
    description: "Measures how independent the asset is from the index by calculating correlation to the market.",
    signature: "correlation_to_market(assetReturns: number[], benchmarkReturns: number[]): number",
    codeExample: `const corr = correlation_to_market(assetReturns, benchmarkReturns);
if (Math.abs(corr) < 0.3) console.log("Low market dependence");`,
    parametersJson: JSON.stringify([
      { name: "assetReturns", type: "number[]", description: "Asset return series" },
      { name: "benchmarkReturns", type: "number[]", description: "Benchmark return series" },
    ]),
    returns: "Correlation coefficient between -1 and 1",
    tagsJson: JSON.stringify(["correlation", "market", "independence"]),
  },
  {
    id: randomUUID(),
    name: "beta_stability",
    category: "technical",
    description: "Measures whether beta remains stable across rolling windows instead of swinging violently.",
    signature: "beta_stability(assetReturns: number[], benchmarkReturns: number[], window?: number): number",
    codeExample: `const stability = beta_stability(assetReturns, benchmarkReturns, 20);
if (stability > 70) console.log("Stable beta profile");`,
    parametersJson: JSON.stringify([
      { name: "assetReturns", type: "number[]", description: "Asset return series" },
      { name: "benchmarkReturns", type: "number[]", description: "Benchmark return series" },
      { name: "window", type: "number", description: "Rolling beta window", optional: true },
    ]),
    returns: "Beta stability score",
    tagsJson: JSON.stringify(["beta", "stability", "market-sensitivity"]),
  },
  {
    id: randomUUID(),
    name: "drawdown_depth",
    category: "technical",
    description: "Measures downside risk by finding the deepest peak-to-trough fall in the lookback period.",
    signature: "drawdown_depth(prices: number[]): number",
    codeExample: `const maxDrawdown = drawdown_depth(prices);
if (maxDrawdown < -15) console.log("Risk profile deteriorating");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Close-price series" },
    ]),
    returns: "Maximum drawdown percentage",
    tagsJson: JSON.stringify(["drawdown", "risk", "downside"]),
  },
  {
    id: randomUUID(),
    name: "hurst_exponent",
    category: "technical",
    description: "Estimates whether the asset behaves more like a trending series or a mean-reverting one.",
    signature: "hurst_exponent(prices: number[]): number",
    codeExample: `const hurst = hurst_exponent(prices);
if (hurst > 0.5) console.log("Trending character");`,
    parametersJson: JSON.stringify([
      { name: "prices", type: "number[]", description: "Close-price series" },
    ]),
    returns: "Hurst exponent value",
    tagsJson: JSON.stringify(["hurst", "trend", "mean-reversion"]),
  },
  {
    id: randomUUID(),
    name: "market_structure_analysis",
    category: "technical",
    description: "Evaluates higher highs, higher lows, lower highs, and lower lows to judge trend integrity.",
    signature: "market_structure_analysis(highs: number[], lows: number[]): number",
    codeExample: `const structure = market_structure_analysis(swingHighs, swingLows);
if (structure > 70) console.log("Trend structure intact");`,
    parametersJson: JSON.stringify([
      { name: "highs", type: "number[]", description: "Swing highs or candle highs" },
      { name: "lows", type: "number[]", description: "Swing lows or candle lows" },
    ]),
    returns: "Structure integrity score between 0 and 100",
    tagsJson: JSON.stringify(["structure", "trend", "swing-analysis"]),
  },

  // Fundamental Analysis
  {
    id: randomUUID(),
    name: "revenue_growth_rate",
    category: "fundamental",
    description: "Validates demand growth by comparing current revenue to a prior comparable period.",
    signature: "revenue_growth_rate(revenue: number, priorRevenue: number, period?: 'quarter' | 'ttm' | 'year'): number",
    codeExample: `const growth = revenue_growth_rate(125_000_000, 100_000_000, "year");
if (growth > 20) console.log("Demand expanding");`,
    parametersJson: JSON.stringify([
      { name: "revenue", type: "number", description: "Current period revenue" },
      { name: "priorRevenue", type: "number", description: "Comparable prior period revenue" },
      { name: "period", type: "'quarter' | 'ttm' | 'year'", description: "Reporting period basis", optional: true },
    ]),
    returns: "Revenue growth percentage",
    tagsJson: JSON.stringify(["growth", "demand", "revenue"]),
  },
  {
    id: randomUUID(),
    name: "organic_revenue_growth",
    category: "fundamental",
    description: "Validates true growth by removing acquisition, divestiture, and currency effects from reported revenue growth.",
    signature: "organic_revenue_growth(revenue: number, priorRevenue: number, acquiredRevenue?: number, fxImpact?: number): number",
    codeExample: `const organic = organic_revenue_growth(125_000_000, 100_000_000, 8_000_000, -1_000_000);`,
    parametersJson: JSON.stringify([
      { name: "revenue", type: "number", description: "Current period revenue" },
      { name: "priorRevenue", type: "number", description: "Comparable prior period revenue" },
      { name: "acquiredRevenue", type: "number", description: "Revenue added through acquisitions", optional: true },
      { name: "fxImpact", type: "number", description: "Foreign exchange impact on revenue", optional: true },
    ]),
    returns: "Organic revenue growth percentage",
    tagsJson: JSON.stringify(["organic-growth", "revenue", "quality"]),
  },
  {
    id: randomUUID(),
    name: "gross_margin",
    category: "fundamental",
    description: "Validates pricing power and moat by measuring gross profit retained after direct costs.",
    signature: "gross_margin(grossProfit: number, revenue: number): number",
    codeExample: `const margin = gross_margin(72_000_000, 120_000_000);`,
    parametersJson: JSON.stringify([
      { name: "grossProfit", type: "number", description: "Revenue minus cost of goods sold" },
      { name: "revenue", type: "number", description: "Current period revenue" },
    ]),
    returns: "Gross margin percentage",
    tagsJson: JSON.stringify(["margin", "pricing-power", "moat"]),
  },
  {
    id: randomUUID(),
    name: "operating_margin",
    category: "fundamental",
    description: "Validates operational efficiency by measuring how much revenue becomes operating income.",
    signature: "operating_margin(operatingIncome: number, revenue: number): number",
    codeExample: `const margin = operating_margin(28_000_000, 120_000_000);`,
    parametersJson: JSON.stringify([
      { name: "operatingIncome", type: "number", description: "Income from core operations" },
      { name: "revenue", type: "number", description: "Current period revenue" },
    ]),
    returns: "Operating margin percentage",
    tagsJson: JSON.stringify(["margin", "efficiency", "operations"]),
  },
  {
    id: randomUUID(),
    name: "free_cash_flow_margin",
    category: "fundamental",
    description: "Validates the ability to convert revenue into cash after operating and capital requirements.",
    signature: "free_cash_flow_margin(freeCashFlow: number, revenue: number): number",
    codeExample: `const margin = free_cash_flow_margin(18_000_000, 120_000_000);`,
    parametersJson: JSON.stringify([
      { name: "freeCashFlow", type: "number", description: "Operating cash flow minus capital expenditures" },
      { name: "revenue", type: "number", description: "Current period revenue" },
    ]),
    returns: "Free cash flow margin percentage",
    tagsJson: JSON.stringify(["cash-flow", "margin", "quality"]),
  },
  {
    id: randomUUID(),
    name: "return_on_invested_capital",
    category: "fundamental",
    description: "Validates capital efficiency by comparing after-tax operating profit to invested capital.",
    signature: "return_on_invested_capital(nopat: number, investedCapital: number): number",
    codeExample: `const roic = return_on_invested_capital(32_000_000, 180_000_000);`,
    parametersJson: JSON.stringify([
      { name: "nopat", type: "number", description: "Net operating profit after tax" },
      { name: "investedCapital", type: "number", description: "Debt plus equity capital invested in operations" },
    ]),
    returns: "ROIC percentage",
    tagsJson: JSON.stringify(["roic", "capital-efficiency", "quality"]),
  },
  {
    id: randomUUID(),
    name: "return_on_equity",
    category: "fundamental",
    description: "Validates shareholder value creation by measuring net income generated per unit of shareholder equity.",
    signature: "return_on_equity(netIncome: number, shareholderEquity: number): number",
    codeExample: `const roe = return_on_equity(22_000_000, 110_000_000);`,
    parametersJson: JSON.stringify([
      { name: "netIncome", type: "number", description: "Reported net income" },
      { name: "shareholderEquity", type: "number", description: "Book value of common shareholder equity" },
    ]),
    returns: "ROE percentage",
    tagsJson: JSON.stringify(["roe", "shareholder-value", "returns"]),
  },
  {
    id: randomUUID(),
    name: "return_on_assets",
    category: "fundamental",
    description: "Validates asset productivity by measuring net income generated from total assets.",
    signature: "return_on_assets(netIncome: number, totalAssets: number): number",
    codeExample: `const roa = return_on_assets(22_000_000, 350_000_000);`,
    parametersJson: JSON.stringify([
      { name: "netIncome", type: "number", description: "Reported net income" },
      { name: "totalAssets", type: "number", description: "Total assets from the balance sheet" },
    ]),
    returns: "ROA percentage",
    tagsJson: JSON.stringify(["roa", "asset-productivity", "returns"]),
  },
  {
    id: randomUUID(),
    name: "free_cash_flow_growth",
    category: "fundamental",
    description: "Validates sustainability of expansion by checking whether free cash flow is growing.",
    signature: "free_cash_flow_growth(freeCashFlow: number, priorFreeCashFlow: number, period?: 'quarter' | 'ttm' | 'year'): number",
    codeExample: `const growth = free_cash_flow_growth(24_000_000, 18_000_000, "ttm");`,
    parametersJson: JSON.stringify([
      { name: "freeCashFlow", type: "number", description: "Current free cash flow" },
      { name: "priorFreeCashFlow", type: "number", description: "Comparable prior period free cash flow" },
      { name: "period", type: "'quarter' | 'ttm' | 'year'", description: "Reporting period basis", optional: true },
    ]),
    returns: "Free cash flow growth percentage",
    tagsJson: JSON.stringify(["cash-flow", "growth", "sustainability"]),
  },
  {
    id: randomUUID(),
    name: "earnings_quality_ratio",
    category: "fundamental",
    description: "Validates quality of reported earnings by comparing cash generation against net income.",
    signature: "earnings_quality_ratio(operatingCashFlow: number, netIncome: number): number",
    codeExample: `const quality = earnings_quality_ratio(30_000_000, 24_000_000);`,
    parametersJson: JSON.stringify([
      { name: "operatingCashFlow", type: "number", description: "Cash generated from operations" },
      { name: "netIncome", type: "number", description: "Reported net income" },
    ]),
    returns: "Cash earnings quality ratio",
    tagsJson: JSON.stringify(["earnings-quality", "cash-flow", "accruals"]),
  },
  {
    id: randomUUID(),
    name: "debt_to_ebitda",
    category: "fundamental",
    description: "Validates leverage risk by comparing debt load against operating earnings capacity.",
    signature: "debt_to_ebitda(totalDebt: number, ebitda: number): number",
    codeExample: `const leverage = debt_to_ebitda(90_000_000, 30_000_000);`,
    parametersJson: JSON.stringify([
      { name: "totalDebt", type: "number", description: "Short-term plus long-term debt" },
      { name: "ebitda", type: "number", description: "Earnings before interest, taxes, depreciation, and amortization" },
    ]),
    returns: "Debt-to-EBITDA multiple",
    tagsJson: JSON.stringify(["debt", "leverage", "risk"]),
  },
  {
    id: randomUUID(),
    name: "interest_coverage_ratio",
    category: "fundamental",
    description: "Validates debt servicing ability by measuring whether EBIT can cover interest expense.",
    signature: "interest_coverage_ratio(ebit: number, interestExpense: number): number",
    codeExample: `const coverage = interest_coverage_ratio(36_000_000, 4_000_000);`,
    parametersJson: JSON.stringify([
      { name: "ebit", type: "number", description: "Earnings before interest and taxes" },
      { name: "interestExpense", type: "number", description: "Interest expense for the same period" },
    ]),
    returns: "Interest coverage multiple",
    tagsJson: JSON.stringify(["debt", "coverage", "solvency"]),
  },
  {
    id: randomUUID(),
    name: "current_ratio",
    category: "fundamental",
    description: "Validates short-term financial health by comparing current assets against current liabilities.",
    signature: "current_ratio(currentAssets: number, currentLiabilities: number): number",
    codeExample: `const liquidity = current_ratio(80_000_000, 45_000_000);`,
    parametersJson: JSON.stringify([
      { name: "currentAssets", type: "number", description: "Assets expected to convert to cash within one year" },
      { name: "currentLiabilities", type: "number", description: "Obligations due within one year" },
    ]),
    returns: "Current ratio multiple",
    tagsJson: JSON.stringify(["liquidity", "balance-sheet", "short-term-health"]),
  },
  {
    id: randomUUID(),
    name: "share_dilution_rate",
    category: "fundamental",
    description: "Validates management alignment by measuring whether existing holders are being diluted.",
    signature: "share_dilution_rate(sharesOutstanding: number, priorSharesOutstanding: number): number",
    codeExample: `const dilution = share_dilution_rate(105_000_000, 100_000_000);`,
    parametersJson: JSON.stringify([
      { name: "sharesOutstanding", type: "number", description: "Current diluted shares outstanding" },
      { name: "priorSharesOutstanding", type: "number", description: "Prior comparable diluted shares outstanding" },
    ]),
    returns: "Share dilution percentage",
    tagsJson: JSON.stringify(["dilution", "alignment", "capital-allocation"]),
  },
  {
    id: randomUUID(),
    name: "insider_ownership_trend",
    category: "fundamental",
    description: "Validates management conviction by checking whether insider ownership is increasing or decreasing.",
    signature: "insider_ownership_trend(insiderOwnershipPct: number, priorInsiderOwnershipPct: number): number",
    codeExample: `const trend = insider_ownership_trend(14.5, 12.8);`,
    parametersJson: JSON.stringify([
      { name: "insiderOwnershipPct", type: "number", description: "Current insider ownership percentage" },
      { name: "priorInsiderOwnershipPct", type: "number", description: "Prior comparable insider ownership percentage" },
    ]),
    returns: "Change in insider ownership percentage points",
    tagsJson: JSON.stringify(["insiders", "management", "conviction"]),
  },
  {
    id: randomUUID(),
    name: "customer_concentration",
    category: "fundamental",
    description: "Validates revenue risk by measuring dependence on the largest customer or customer group.",
    signature: "customer_concentration(topCustomerRevenue: number, revenue: number): number",
    codeExample: `const concentration = customer_concentration(35_000_000, 120_000_000);`,
    parametersJson: JSON.stringify([
      { name: "topCustomerRevenue", type: "number", description: "Revenue from the largest customer or customer group" },
      { name: "revenue", type: "number", description: "Current period revenue" },
    ]),
    returns: "Customer concentration percentage",
    tagsJson: JSON.stringify(["customer-risk", "revenue-risk", "concentration"]),
  },
  {
    id: randomUUID(),
    name: "research_and_development_intensity",
    category: "fundamental",
    description: "Validates future innovation pipeline by measuring R&D spend relative to revenue.",
    signature: "research_and_development_intensity(rAndDExpense: number, revenue: number): number",
    codeExample: `const intensity = research_and_development_intensity(18_000_000, 120_000_000);`,
    parametersJson: JSON.stringify([
      { name: "rAndDExpense", type: "number", description: "Research and development expense" },
      { name: "revenue", type: "number", description: "Current period revenue" },
    ]),
    returns: "R&D intensity percentage",
    tagsJson: JSON.stringify(["innovation", "r-and-d", "pipeline"]),
  },
  {
    id: randomUUID(),
    name: "revenue_per_employee",
    category: "fundamental",
    description: "Validates organizational efficiency by measuring revenue generated per employee.",
    signature: "revenue_per_employee(revenue: number, employeeCount: number): number",
    codeExample: `const efficiency = revenue_per_employee(120_000_000, 420);`,
    parametersJson: JSON.stringify([
      { name: "revenue", type: "number", description: "Current period revenue" },
      { name: "employeeCount", type: "number", description: "Current employee count" },
    ]),
    returns: "Revenue per employee",
    tagsJson: JSON.stringify(["efficiency", "headcount", "productivity"]),
  },
  {
    id: randomUUID(),
    name: "enterprise_value_to_free_cash_flow",
    category: "fundamental",
    description: "Validates cash-based valuation by comparing enterprise value to free cash flow.",
    signature: "enterprise_value_to_free_cash_flow(enterpriseValue: number, freeCashFlow: number): number",
    codeExample: `const evFcf = enterprise_value_to_free_cash_flow(900_000_000, 60_000_000);`,
    parametersJson: JSON.stringify([
      { name: "enterpriseValue", type: "number", description: "Market capitalization plus debt minus cash" },
      { name: "freeCashFlow", type: "number", description: "Operating cash flow minus capital expenditures" },
    ]),
    returns: "EV/FCF multiple",
    tagsJson: JSON.stringify(["valuation", "cash-flow", "multiple"]),
  },
  {
    id: randomUUID(),
    name: "peg_ratio",
    category: "fundamental",
    description: "Validates whether growth justifies valuation by comparing P/E against earnings growth.",
    signature: "peg_ratio(priceToEarnings: number, earningsGrowthRate: number): number",
    codeExample: `const peg = peg_ratio(24, 18);`,
    parametersJson: JSON.stringify([
      { name: "priceToEarnings", type: "number", description: "Current P/E multiple" },
      { name: "earningsGrowthRate", type: "number", description: "Expected or realized earnings growth percentage" },
    ]),
    returns: "PEG ratio",
    tagsJson: JSON.stringify(["valuation", "growth", "peg"]),
  },

  // Sentiment
  {
    id: randomUUID(),
    name: "news_sentiment_analysis",
    category: "sentiment",
    description: "Scores positive or negative tone in financial news articles for a shortlisted stock.",
    signature: "news_sentiment_analysis(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = news_sentiment_analysis("NVDA", evidence, 7);
// score ranges from -5 to +5`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Normalized articles, source credibility, recency, and event tags" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["news", "nlp", "sentiment"]),
  },
  {
    id: randomUUID(),
    name: "social_media_sentiment",
    category: "sentiment",
    description: "Scores public opinion from X, Reddit, LinkedIn, Facebook, and similar social channels.",
    signature: "social_media_sentiment(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = social_media_sentiment("TSLA", evidence, 3);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Posts, engagement, reach, source reputation, and bot-risk signals" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["social", "public-opinion", "sentiment"]),
  },
  {
    id: randomUUID(),
    name: "search_trend_analysis",
    category: "sentiment",
    description: "Scores rising public interest using search volume and query quality data.",
    signature: "search_trend_analysis(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = search_trend_analysis("AAPL", evidence, 14);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Search volume, breakout queries, regional interest, and intent labels" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["search", "attention", "trend"]),
  },
  {
    id: randomUUID(),
    name: "options_market_sentiment",
    category: "sentiment",
    description: "Scores expectations implied by options traders through put/call skew, IV, and unusual flow.",
    signature: "options_market_sentiment(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = options_market_sentiment("AMD", evidence, 5);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Options chain, put/call ratio, IV surface, and unusual options activity" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["options", "flow", "implied-expectations"]),
  },
  {
    id: randomUUID(),
    name: "institutional_fund_flow_analysis",
    category: "sentiment",
    description: "Scores where large investors are moving capital using fund flows, block trades, and ownership changes.",
    signature: "institutional_fund_flow_analysis(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = institutional_fund_flow_analysis("MSFT", evidence, 30);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "ETF flows, 13F changes, block trades, and institutional ownership signals" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["institutional", "fund-flow", "capital"]),
  },
  {
    id: randomUUID(),
    name: "analyst_rating_sentiment",
    category: "sentiment",
    description: "Scores analyst upgrades, downgrades, target-price revisions, and consensus drift.",
    signature: "analyst_rating_sentiment(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = analyst_rating_sentiment("META", evidence, 30);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Ratings, target prices, revision history, analyst credibility, and consensus trend" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["analyst", "ratings", "target-price"]),
  },
  {
    id: randomUUID(),
    name: "earnings_call_sentiment",
    category: "sentiment",
    description: "Scores management confidence and tone during earnings calls.",
    signature: "earnings_call_sentiment(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = earnings_call_sentiment("GOOGL", evidence, 90);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Prepared remarks, Q&A transcripts, uncertainty terms, and guidance language" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["earnings-call", "management-tone", "guidance"]),
  },
  {
    id: randomUUID(),
    name: "insider_trading_analysis",
    category: "sentiment",
    description: "Scores executive and director buying or selling behavior.",
    signature: "insider_trading_analysis(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = insider_trading_analysis("CRM", evidence, 60);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Form 4 transactions, role seniority, trade size, recurrence, and timing" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["insiders", "management", "transactions"]),
  },
  {
    id: randomUUID(),
    name: "technical_sentiment_indicators",
    category: "sentiment",
    description: "Scores market psychology reflected in price behavior, breadth, volatility, squeezes, and capitulation.",
    signature: "technical_sentiment_indicators(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = technical_sentiment_indicators("NFLX", evidence, 10);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Technical metric outputs, breadth, volatility, and price-action regimes" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["technical-sentiment", "market-psychology", "price-action"]),
  },
  {
    id: randomUUID(),
    name: "consumer_review_sentiment",
    category: "sentiment",
    description: "Scores customer opinions about products and services from reviews and satisfaction signals.",
    signature: "consumer_review_sentiment(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = consumer_review_sentiment("SBUX", evidence, 30);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Reviews, ratings, complaint themes, satisfaction changes, and review velocity" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["consumer", "reviews", "customer-sentiment"]),
  },
  {
    id: randomUUID(),
    name: "supply_chain_sentiment",
    category: "sentiment",
    description: "Scores supplier, logistics, inventory, and manufacturing signals.",
    signature: "supply_chain_sentiment(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = supply_chain_sentiment("TSM", evidence, 45);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Supplier commentary, logistics delays, inventory stress, and manufacturing indicators" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["supply-chain", "logistics", "manufacturing"]),
  },
  {
    id: randomUUID(),
    name: "influencer_community_forum_analysis",
    category: "sentiment",
    description: "Scores deep discussions from niche communities, forums, and influential commentators.",
    signature: "influencer_community_forum_analysis(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = influencer_community_forum_analysis("PLTR", evidence, 14);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Forum threads, expert posts, influencer reach, narrative depth, and community conviction" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["community", "forums", "influencers"]),
  },
  {
    id: randomUUID(),
    name: "macroeconomic_sentiment_analysis",
    category: "sentiment",
    description: "Scores sentiment implied by economic indicators and the macro backdrop.",
    signature: "macroeconomic_sentiment_analysis(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = macroeconomic_sentiment_analysis("JPM", evidence, 30);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Rates, inflation, employment, growth, policy, and sector sensitivity" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["macro", "economy", "policy"]),
  },
  {
    id: randomUUID(),
    name: "alternative_data_sentiment",
    category: "sentiment",
    description: "Scores real-world behavioral signals from alternative data sources.",
    signature: "alternative_data_sentiment(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = alternative_data_sentiment("UBER", evidence, 21);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "App usage, web traffic, card spend, foot traffic, sensor data, and other behavioral signals" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["alternative-data", "behavior", "real-world-signals"]),
  },
  {
    id: randomUUID(),
    name: "prediction_market_analysis",
    category: "sentiment",
    description: "Scores what people are willing to bet on happening using prediction and event market probabilities.",
    signature: "prediction_market_analysis(symbol: string, evidence: SentimentEvidence, lookbackDays?: number): number",
    codeExample: `const score = prediction_market_analysis("COIN", evidence, 14);`,
    parametersJson: JSON.stringify([
      { name: "symbol", type: "string", description: "Stock symbol under analysis" },
      { name: "evidence", type: "SentimentEvidence", description: "Prediction market probabilities, event-market odds, liquidity, and probability shifts" },
      { name: "lookbackDays", type: "number", description: "Evidence lookback window", optional: true },
    ]),
    returns: "Segment score from -5 to +5",
    tagsJson: JSON.stringify(["prediction-market", "probability", "odds"]),
  },

  // Orderbook
  {
    id: randomUUID(),
    name: "order_imbalance",
    category: "orderbook",
    description: "Measures the imbalance between bid and ask volume at the top N levels of the orderbook.",
    signature: "order_imbalance(bids: Array<[price: number, qty: number]>, asks: Array<[price: number, qty: number]>, levels?: number): number",
    codeExample: `const bids = [[100.0, 500], [99.9, 300], [99.8, 200]];
const asks = [[100.1, 400], [100.2, 600], [100.3, 100]];
const oi = order_imbalance(bids, asks, 3);
// oi => 0.09 (slight buy pressure)`,
    parametersJson: JSON.stringify([
      { name: "bids", type: "Array<[number, number]>", description: "Bid levels [price, qty]" },
      { name: "asks", type: "Array<[number, number]>", description: "Ask levels [price, qty]" },
      { name: "levels", type: "number", description: "Number of levels to consider (default 5)", optional: true },
    ]),
    returns: "Imbalance ratio in range [-1, 1]",
    tagsJson: JSON.stringify(["orderbook", "microstructure", "pressure", "L2"]),
  },
  {
    id: randomUUID(),
    name: "mid_price",
    category: "orderbook",
    description: "Computes the mid-price as the arithmetic mean of best bid and ask.",
    signature: "mid_price(bestBid: number, bestAsk: number): number",
    codeExample: `const mid = mid_price(100.0, 100.1); // => 100.05`,
    parametersJson: JSON.stringify([
      { name: "bestBid", type: "number", description: "Best bid price" },
      { name: "bestAsk", type: "number", description: "Best ask price" },
    ]),
    returns: "Mid price",
    tagsJson: JSON.stringify(["orderbook", "price", "spread"]),
  },
  {
    id: randomUUID(),
    name: "spread_bps",
    category: "orderbook",
    description: "Calculates the bid-ask spread in basis points relative to mid price.",
    signature: "spread_bps(bestBid: number, bestAsk: number): number",
    codeExample: `const bps = spread_bps(100.0, 100.1);
// bps => 1.0 (1 basis point)`,
    parametersJson: JSON.stringify([
      { name: "bestBid", type: "number", description: "Best bid price" },
      { name: "bestAsk", type: "number", description: "Best ask price" },
    ]),
    returns: "Spread in basis points",
    tagsJson: JSON.stringify(["orderbook", "spread", "liquidity", "cost"]),
  },
  {
    id: randomUUID(),
    name: "book_depth",
    category: "orderbook",
    description: "Computes cumulative volume at each price level within a tick range from mid.",
    signature: "book_depth(side: 'bid' | 'ask', levels: Array<[price: number, qty: number]>, maxTicksFromMid: number): number",
    codeExample: `const depth = book_depth('bid', bidLevels, 10);
// depth => 15000 (cumulative bid volume within 10 ticks)`,
    parametersJson: JSON.stringify([
      { name: "side", type: "'bid' | 'ask'", description: "Which side to measure" },
      { name: "levels", type: "Array<[number, number]>", description: "Price levels" },
      { name: "maxTicksFromMid", type: "number", description: "Depth range in ticks" },
    ]),
    returns: "Cumulative volume",
    tagsJson: JSON.stringify(["orderbook", "depth", "liquidity", "L2"]),
  },

  // Utility
  {
    id: randomUUID(),
    name: "clamp",
    category: "utility",
    description: "Clamps a numeric value to a specified [min, max] range.",
    signature: "clamp(value: number, min: number, max: number): number",
    codeExample: `clamp(150, 0, 100); // => 100
clamp(-5, 0, 100);  // => 0
clamp(42, 0, 100);  // => 42`,
    parametersJson: JSON.stringify([
      { name: "value", type: "number", description: "Input value" },
      { name: "min", type: "number", description: "Minimum bound" },
      { name: "max", type: "number", description: "Maximum bound" },
    ]),
    returns: "Clamped value",
    tagsJson: JSON.stringify(["math", "bounds", "normalization"]),
  },
  {
    id: randomUUID(),
    name: "round_tick",
    category: "utility",
    description: "Rounds a price to the nearest valid tick size.",
    signature: "round_tick(price: number, tickSize: number): number",
    codeExample: `round_tick(100.037, 0.05); // => 100.05
round_tick(99.963, 0.05); // => 99.95`,
    parametersJson: JSON.stringify([
      { name: "price", type: "number", description: "Raw price" },
      { name: "tickSize", type: "number", description: "Minimum price increment" },
    ]),
    returns: "Price rounded to nearest tick",
    tagsJson: JSON.stringify(["price", "tick", "exchange", "precision"]),
  },
];

async function seed() {
  console.log(`Seeding ${functions.length} functions...`);

  for (const fn of functions) {
    await db
      .insert(functionsTable)
      .values(fn)
      .onConflictDoNothing();
  }

  console.log("Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
