// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-gradient/Gradient.tsx": () => import("../components/mockups/landing-gradient/Gradient.tsx"),
  "./components/mockups/landing-minimal/Minimal.tsx": () => import("../components/mockups/landing-minimal/Minimal.tsx"),
  "./components/mockups/landing-terminal/Terminal.tsx": () => import("../components/mockups/landing-terminal/Terminal.tsx")
};
